<?php
//DAF data
$DAF_2021_XF = [
    'id' => 'daf_2021_xf',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF 2021 XF',
    'titre_moteur' => 'Engine Power',
    'moteur' => '367 cv (270kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '800 L',
    'image' => 'images/trucks/DAF/DAF_2021_XF_pré-configuré.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XF',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€114 280',    
];

$DAF_XF105_Space = [
    'id' => 'daf_xf105_space',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF XF105 Space',
    'titre_moteur' => 'Engine Power',
    'moteur' => '360 cv (265kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 000 L',
    'image' => 'images/trucks/DAF/DAF_XF105_space_cab_plus.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Space',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€117 270',    
];

$DAF_XF_Space = [
    'id' => 'daf_xf_space',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF XF Space',
    'titre_moteur' => 'Engine Power',
    'moteur' => '370 cv (270kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 400 L',
    'image' => 'images/trucks/DAF/DAF_XF_space.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Space',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€127 690',    
];

$DAF_XF105_Space_Cab_Plus = [
    'id' => 'daf_xf105_space_cab_plus',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF XF105 Space Cab Plus',
    'titre_moteur' => 'Engine Power',
    'moteur' => '460 cv (340kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 L',
    'image' => 'images/trucks/DAF/DAF_XF105_space_cab_plus.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2 / Space Cab Plus',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '10',
    'titre_prix' => 'In-Game Price',
    'prix' => '€179 661',    
];

$DAF_XF_Space_Aero_4x2 = [
    'id' => 'daf_xf_space_aero_4x2',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF XF Space Aero',
    'titre_moteur' => 'Engine Power',
    'moteur' => '530 cv (390kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 400 L',
    'image' => 'images/trucks/DAF/DAF_XF_space_Aero.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Space Aero',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '18',
    'titre_prix' => 'In-Game Price',
    'prix' => '€181 750',    
];

$DAF_XF_Space_Aero_6x2 = [
    'id' => 'daf_xf_space_aero_6x2',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF XF Space Aero',
    'titre_moteur' => 'Engine Power',
    'moteur' => '480 cv (355kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '800 L',
    'image' => 'images/trucks/DAF/DAF_XF_Space_Aero2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2 / Space Aero',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '€183 715',    
];

$DAF_2021_XG = [
    'id' => 'daf_2021_xg',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF 2021 XG',
    'titre_moteur' => 'Engine Power',
    'moteur' => '449 cv (330kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 245 L',
    'image' => 'images/trucks/DAF/DAF_2021_XG.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XG',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '15',
    'titre_prix' => 'In-Game Price',
    'prix' => '€198 530',    
];

$DAF_XF_Super_Space_4x2 = [
    'id' => 'daf_xf_super_space_4x2',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF XF Super Space',
    'titre_moteur' => 'Engine Power',
    'moteur' => '530 cv (390kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 400 L',
    'image' => 'images/trucks/DAF/DAF_XF105_Super_Space.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Super Space',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '18',
    'titre_prix' => 'In-Game Price',
    'prix' => '€209 770',    
];

$DAF_XF_Super_Space_6x2 = [
    'id' => 'daf_xf_super_space_6x2',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF XF Super Space',
    'titre_moteur' => 'Engine Power',
    'moteur' => '530 cv (390kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '800 L',
    'image' => 'images/trucks/DAF/DAF_XF_Super_Space2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2 Taglift / Super Space',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '18',
    'titre_prix' => 'In-Game Price',
    'prix' => '€220 885',    
];

$DAF_XF105_Super_Space = [
    'id' => 'daf_xf105_super_space',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF XF105 Super Space',
    'titre_moteur' => 'Engine Power',
    'moteur' => '510 cv (375kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 000 L',
    'image' => 'images/trucks/DAF/DAF_XF105_Super_Space.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Super Space',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '€233 510',    
];

$DAF_2021_XG_Plus = [
    'id' => 'daf_2021_xg_plus',
    'marque' => 'DAF',
    'logo' => 'images/trucks/DAF/DAF_logo.png',
    'titre' => 'DAF 2021 XG+',
    'titre_moteur' => 'Engine Power',
    'moteur' => '530 cv (390kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 465 L',
    'image' => 'images/trucks/DAF/DAF_2021_XG+.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XG+',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '29',
    'titre_prix' => 'In-Game Price',
    'prix' => '€256 845',    
];

//Iveco data
$Iveco_Stralis_Active_Space_310 = [
    'id' => 'iveco_stralis_active_space_310',
    'marque' => 'Iveco',
    'logo' => 'images/trucks/Iveco/Iveco_logo.png',
    'titre' => 'Iveco Stralis Active Space',
    'titre_moteur' => 'Engine Power',
    'moteur' => '310 cv (228kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1300 L',
    'image' => 'images/trucks/Iveco/Iveco_Stralis_Active_Space.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Active Space',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€97 255',    
];

$Iveco_Stralis_Active_Space_450_4x2 = [
    'id' => 'iveco_stralis_active_space_450_4x2',
    'marque' => 'Iveco',
    'logo' => 'images/trucks/Iveco/Iveco_logo.png',
    'titre' => 'Iveco Stralis Active Space',
    'titre_moteur' => 'Engine Power',
    'moteur' => '450 cv (331kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1300 L',
    'image' => 'images/trucks/Iveco/Iveco_Stralis_Active_Space_2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Active Space',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12',
    'titre_prix' => 'In-Game Price',
    'prix' => '€113 575',    
];

$Iveco_Stralis_Active_Super = [
    'id' => 'iveco_stralis_active_super',
    'marque' => 'Iveco',
    'logo' => 'images/trucks/Iveco/Iveco_logo.png',
    'titre' => 'Iveco Stralis Active Super',
    'titre_moteur' => 'Engine Power',
    'moteur' => '450 cv (331kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '400 L',
    'image' => 'images/trucks/Iveco/Iveco_Stralis_Active_Super.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2/4 / Active Super',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12',
    'titre_prix' => 'In-Game Price',
    'prix' => '€144 725',    
];

$Iveco_Stralis_Active_Space_450_6x4 = [
    'id' => 'iveco_stralis_active_space_450_6x4',
    'marque' => 'Iveco',
    'logo' => 'images/trucks/Iveco/Iveco_logo.png',
    'titre' => 'Iveco Stralis Active Space',
    'titre_moteur' => 'Engine Power',
    'moteur' => '450 cv (331kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '400 L',
    'image' => 'images/trucks/Iveco/Iveco_Stralis_Active_Space_3.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x4 / Active Space',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '€149 260',    
];

$Iveco_Stralis_HiWay_310 = [
    'id' => 'iveco_stralis_hiway_310',
    'marque' => 'Iveco',
    'logo' => 'images/trucks/Iveco/Iveco_logo.png',
    'titre' => 'Iveco Stralis Hi-Way',
    'titre_moteur' => 'Engine Power',
    'moteur' => '310 cv (228kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1200 L',
    'image' => 'images/trucks/Iveco/Iveco_Stralis_Hi-Way.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Hi-Way',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€157 945',    
];

$Iveco_Stralis_Active_Space_Super_450 = [
    'id' => 'iveco_stralis_active_space_super_450',
    'marque' => 'Iveco',
    'logo' => 'images/trucks/Iveco/Iveco_logo.png',
    'titre' => 'Iveco Stralis Active Space Super',
    'titre_moteur' => 'Engine Power',
    'moteur' => '450 cv (331kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1300 L',
    'image' => 'images/trucks/Iveco/Iveco_Stralis_Active_Space_Super.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Active Space Super',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12',
    'titre_prix' => 'In-Game Price',
    'prix' => '€167 265',    
];

$Iveco_Stralis_HiWay_560 = [
    'id' => 'iveco_stralis_hiway_560',
    'marque' => 'Iveco',
    'logo' => 'images/trucks/Iveco/Iveco_logo.png',
    'titre' => 'Iveco Stralis Hi-Way',
    'titre_moteur' => 'Engine Power',
    'moteur' => '560 cv (412kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1200 L',
    'image' => 'images/trucks/Iveco/Iveco_Stralis_Hi-Way_2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / Hi-Way',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '€178 995',    
];

$Iveco_Stralis_Active_Space_Super_560 = [
    'id' => 'iveco_stralis_active_space_super_560',
    'marque' => 'Iveco',
    'logo' => 'images/trucks/Iveco/Iveco_logo.png',
    'titre' => 'Iveco Stralis Active Space Super',
    'titre_moteur' => 'Engine Power',
    'moteur' => '560 cv (412kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '400 L',
    'image' => 'images/trucks/Iveco/Iveco_Stralis_Active_Space_Super_2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2/4 / Active Space Super',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '€199 965',    
];

//MAN data
$MAN_TGX_Euro_5_XL = [
    'id' => 'man_tgx_euro_5_xl',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 5 XL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '320 cv (235kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 250 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_5_XL.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XL',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€99 965',    
];

$MAN_TGX_Euro_6_XL = [
    'id' => 'man_tgx_euro_6_xl',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 6 XL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '330 cv (243kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 160 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_6_XL.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XL',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€106 755',    
];

$MAN_TGX_GN = [
    'id' => 'man_tgx_gn',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX GN',
    'titre_moteur' => 'Engine Power',
    'moteur' => '330 cv (243kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '850 L',
    'image' => 'images/trucks/MAN/MAN_TGX_GN.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / GN',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€116 585',    
];

$MAN_TGX_Euro_5_XLX = [
    'id' => 'man_tgx_euro_5_xlx',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 5 XLX',
    'titre_moteur' => 'Engine Power',
    'moteur' => '480 cv (353kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 250 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_5_XLX.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XLX',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12',
    'titre_prix' => 'In-Game Price',
    'prix' => '€138 935',    
];

$MAN_TGX_Euro_6_XL_6x2 = [
    'id' => 'man_tgx_euro_6_xl_6x2',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 6 XL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '400 cv (294kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '450 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_6_XL2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2/4 Midlift / XL',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12',
    'titre_prix' => 'In-Game Price',
    'prix' => '€148 695',    
];

$MAN_TGX_Euro_5_XL_6x4 = [
    'id' => 'man_tgx_euro_5_xl_6x4',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 5 XL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '440 cv (324kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '700 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_5_XL2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x4 / XL',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '€152 100',    
];

$MAN_TGX_XLX = [
    'id' => 'man_tgx_xlx',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX XLX',
    'titre_moteur' => 'Engine Power',
    'moteur' => '540 cv (397kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '450 L',
    'image' => 'images/trucks/MAN/MAN_TGX_XLX.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2/4 / XLX',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '€154 335',    
];

$MAN_TGX_Euro_6_XLX = [
    'id' => 'man_tgx_euro_6_xlx',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 6 XLX',
    'titre_moteur' => 'Engine Power',
    'moteur' => '460 cv (343kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 160 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_6_XLX.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XLX',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12',
    'titre_prix' => 'In-Game Price',
    'prix' => '€158 115',    
];

$MAN_TGX_Euro_5_XXL = [
    'id' => 'man_tgx_euro_5_xxl',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 5 XXL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '540 cv (397kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 250 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_5_XXL.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XXL',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '€164 915',    
];

$MAN_TGX_Euro_6_XXL = [
    'id' => 'man_tgx_euro_6_xxl',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 6 XXL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '540 cv (403kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 160 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_6_XXL.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / XXL',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '18',
    'titre_prix' => 'In-Game Price',
    'prix' => '€171 720',    
];

$MAN_TGX_Euro_5_XXL_6x2 = [
    'id' => 'man_tgx_euro_5_xxl_6x2',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 5 XXL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '540 cv (397kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '450 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_6_XXL2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2/4 / XXL',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '€178 035',    
];

$MAN_TGX_GM = [
    'id' => 'man_tgx_gm',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX GM',
    'titre_moteur' => 'Engine Power',
    'moteur' => '430 cv (316kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '400 L',
    'image' => 'images/trucks/MAN/MAN_TGX_GM.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x2/2 Taglift / GM',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '15',
    'titre_prix' => 'In-Game Price',
    'prix' => '€188 340',    
];

$MAN_TGX_Euro_6_XLX_6x4 = [
    'id' => 'man_tgx_euro_6_xlx_6x4',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 6 XLX',
    'titre_moteur' => 'Engine Power',
    'moteur' => '500 cv (373kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '400 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_6_XLX2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '6x4 / XLX',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '€199 180',    
];

$MAN_TGX_GX = [
    'id' => 'man_tgx_gx',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX GX',
    'titre_moteur' => 'Engine Power',
    'moteur' => '640 cv (471kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '850 L',
    'image' => 'images/trucks/MAN/MAN_TGX_GX.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '4x2 / GX',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '20',
    'titre_prix' => 'In-Game Price',
    'prix' => '€212 645',    
];

$MAN_TGX_Euro_6_XXL_8x4 = [
    'id' => 'man_tgx_euro_6_xxl_8x4',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX Euro 6 XXL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '640 cv (471kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '960 L',
    'image' => 'images/trucks/MAN/MAN_TGX_Euro_6_XL.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '8x4/4 Midlift / XXL',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '20',
    'titre_prix' => 'In-Game Price',
    'prix' => '€259 505',    
];

$MAN_TGX_GX_8x4 = [
    'id' => 'man_tgx_gx_8x4',
    'marque' => 'MAN',
    'logo' => 'images/trucks/MAN/MAN_logo.png',
    'titre' => 'MAN TGX GX',
    'titre_moteur' => 'Engine Power',
    'moteur' => '540 cv (397kW)',
    'titre_essence' => 'Tank Capacity',
    'essence' => '960 L',
    'image' => 'images/trucks/MAN/MAN_TGX_GX2.jpg',
    'titre_modele' => 'Chassis / Cabin',
    'modele' => '8x4/4 Midlift / GX',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '18',
    'titre_prix' => 'In-Game Price',
    'prix' => '€263 680',    
];

//Mercedes data
$Mercedes_Actros_Low_Roof_Sleeper = [
    'id' => 'mercedes_actros_low_roof_sleeper',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '320 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_Actros_Low_Roof_Sleeper.jpg',
    'titre_modele' => 'Model',
    'modele' => 'Actros Low Roof Sleeper',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '116 005 €',
];

$Mercedes_New_Actros_StreamSpace = [
    'id' => 'mercedes_new_actros_streamspace',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz New Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '421 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 140 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_New_Actros_StreamSpace.jpg',
    'titre_modele' => 'Model',
    'modele' => 'New Actros StreamSpace',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '118 775 €',
];

$Mercedes_Actros_Low_Roof_Sleeper_6x4 = [
    'id' => 'mercedes_actros_low_roof_sleeper_6x4',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '476 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_Actros_Low_Roof_Sleeper_6x4.jpg',
    'titre_modele' => 'Model',
    'modele' => 'Actros Low Roof Sleeper (6x4)',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '165 360 €',
];

$Mercedes_Actros_High_Roof_Sleeper = [
    'id' => 'mercedes_actros_high_roof_sleeper',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '510 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_Actros_High_Roof_Sleeper.jpg',
    'titre_modele' => 'Model',
    'modele' => 'Actros High Roof Sleeper',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '170 695 €',
];

$Mercedes_Actros_High_Roof_Sleeper_6x2_4 = [
    'id' => 'mercedes_actros_high_roof_sleeper_6x2_4',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '510 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '400 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_Actros_High_Roof_Sleeper_6x2-4.jpg',
    'titre_modele' => 'Model',
    'modele' => 'Actros High Roof Sleeper (6x2/4)',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '184 445 €',
];

$Mercedes_Actros_MegaSpace = [
    'id' => 'mercedes_actros_megaspace',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '510 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_Actros_MegaSpace.jpg',
    'titre_modele' => 'Model',
    'modele' => 'Actros MegaSpace',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '198 965 €',
];

$Mercedes_New_Actros_GigaSpace = [
    'id' => 'mercedes_new_actros_gigaspace',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz New Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '510 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1 140 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_New_Actros_GigaSpace.jpg',
    'titre_modele' => 'Model',
    'modele' => 'New Actros GigaSpace',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12',
    'titre_prix' => 'In-Game Price',
    'prix' => '201 875 €',
];

$Mercedes_New_Actros_BigSpace = [
    'id' => 'mercedes_new_actros_bigspace',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz New Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '476 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '890 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_New_Actros_BigSpace.jpg',
    'titre_modele' => 'Model',
    'modele' => 'New Actros BigSpace',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '206 440 €',
];

$Mercedes_Actros_High_Roof_Sleeper_6x4 = [
    'id' => 'mercedes_actros_high_roof_sleeper_6x4',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '476 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_Actros_High_Roof_Sleeper_6x4.jpg',
    'titre_modele' => 'Model',
    'modele' => 'Actros High Roof Sleeper (6x4)',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '14',
    'titre_prix' => 'In-Game Price',
    'prix' => '206 800 €',
];

$Mercedes_Actros_MegaSpace_6x2_4 = [
    'id' => 'mercedes_actros_megaspace_6x2_4',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '510 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '400 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_Actros_MegaSpace_6x2-4.jpg',
    'titre_modele' => 'Model',
    'modele' => 'Actros MegaSpace (6x2/4)',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '20',
    'titre_prix' => 'In-Game Price',
    'prix' => '214 270 €',
];

$Mercedes_Actros_MegaSpace_598cv = [
    'id' => 'mercedes_actros_megaspace_598cv',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '598 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_Actros_MegaSpace_598cv.jpg',
    'titre_modele' => 'Model',
    'modele' => 'Actros MegaSpace (598 cv)',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '20',
    'titre_prix' => 'In-Game Price',
    'prix' => '220 905 €',
];

$Mercedes_New_Actros_GigaSpace_8x4 = [
    'id' => 'mercedes_new_actros_gigaspace_8x4',
    'marque' => 'Mercedes Benz',
    'logo' => 'images/trucks/MB/Mercedes_Benz_logo.png',
    'titre' => 'Mercedes-Benz New Actros',
    'titre_moteur' => 'Engine Power',
    'moteur' => '517 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '960 L',
    'image' => 'images/trucks/MB/Mercedes-Benz_New_Actros_GigaSpace_8x4.jpg',
    'titre_modele' => 'Model',
    'modele' => 'New Actros GigaSpace (8x4/4 Midlift)',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '274 230 €',
];

//Renault data
$Renault_Magnum_Excellence = [
    'id' => 'renault_magnum_excellence',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault Magnum Excellence',
    'titre_moteur' => 'Engine Power',
    'moteur' => '440 - 520 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1200 l',
    'image' => 'images/trucks/Renault/Renault_Magnum_Excellence.jpg',
    'titre_modele' => 'Excellence',
    'modele' => 'Chassis 4x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Used Market Only',    
];

$Renault_Magnum_Excellence1 = [
    'id' => 'renault_magnum_excellence_6x2',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault Magnum Excellence',
    'titre_moteur' => 'Engine Power',
    'moteur' => '440 - 520 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 l',
    'image' => 'images/trucks/Renault/Renault_Magnum_Excellence1.jpg',
    'titre_modele' => 'Excellence',
    'modele' => 'Chassis 6x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '8',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Used Market Only',    
];

$Renault_Magnum_Excellence2 = [
    'id' => 'renault_magnum_excellence_6x2_4',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault Magnum Excellence',
    'titre_moteur' => 'Engine Power',
    'moteur' => '440 - 520 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 l',
    'image' => 'images/trucks/Renault/Renault_Magnum_Excellence2.jpg',
    'titre_modele' => 'Excellence',
    'modele' => 'Chassis 6x2/4',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '10',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Used Market Only',    
];

$Renault_Magnum_Excellence3 = [
    'id' => 'renault_magnum_excellence_6x2_taglift',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault Magnum Excellence',
    'titre_moteur' => 'Engine Power',
    'moteur' => '440 - 520 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 l',
    'image' => 'images/trucks/Renault/Renault_Magnum_Excellence3.jpg',
    'titre_modele' => 'Excellence',
    'modele' => 'Chassis 6x2 Taglift',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '10',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Used Market Only',    
];

$Renault_Premium_High_Roof = [
    'id' => 'renault_premium_high_roof',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault Premium High Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '380 - 460 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1000 l',
    'image' => 'images/trucks/Renault/Renault_Prenium_High_Roof.jpg',
    'titre_modele' => 'High Roof',
    'modele' => 'Chassis 4x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '8',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Used Market Only',    
];

$Renault_Premium_High_Roof2 = [
    'id' => 'renault_premium_high_roof_6x2',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault Premium High Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '380 - 460 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 l',
    'image' => 'images/trucks/Renault/Renault_Prenium_High_Roof2.jpg',
    'titre_modele' => 'High Roof',
    'modele' => 'Chassis 6x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '8',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Used Market Only',    
];

$Renault_Premium_Normal_Roof = [
    'id' => 'renault_premium_normal_roof',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault Premium Normal Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '380 - 460 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1000 l',
    'image' => 'images/trucks/Renault/Renault_Prenium_Normal_Roof.jpg',
    'titre_modele' => 'Normal Roof',
    'modele' => 'Chassis 4x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Used Market Only',    
];

$Renault_Premium_Normal_Roof2 = [
    'id' => 'renault_premium_normal_roof_6x2',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault Premium Normal Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '380 - 460 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 l',
    'image' => 'images/trucks/Renault/Renault_Prenium_Normal_Roof2.jpg',
    'titre_modele' => 'Normal Roof',
    'modele' => 'Chassis 6x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '8',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Used Market Only',    
];

$Renault_T_High_Sleeper = [
    'id' => 'renault_t_high_sleeper',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault T High Sleeper',
    'titre_moteur' => 'Engine Power',
    'moteur' => '480 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1045 l',
    'image' => 'images/trucks/Renault/Renault_T_High_Sleeper.jpg',
    'titre_modele' => 'T High Sleeper',
    'modele' => 'Chassis 4x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '€202,485.-',    
];

$Renault_T_High_Sleeper2 = [
    'id' => 'renault_t_high_sleeper_6x2_taglift',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault T High Sleeper',
    'titre_moteur' => 'Engine Power',
    'moteur' => '520 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '765 l',
    'image' => 'images/trucks/Renault/Renault_T_High_Sleeper2.jpg',
    'titre_modele' => 'T High Sleeper',
    'modele' => 'Chassis 6x2 Taglift',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '18',
    'titre_prix' => 'In-Game Price',
    'prix' => '€206,673.-',    
];

$Renault_T_Sleeper = [
    'id' => 'renault_t_sleeper',
    'marque' => 'Renault',
    'logo' => 'images/trucks/Renault/Renault_Trucks_nouveau_logo.jpg',
    'titre' => 'Renault T Sleeper',
    'titre_moteur' => 'Engine Power',
    'moteur' => '380 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1045 l',
    'image' => 'images/trucks/Renault/Renault_T_Sleeper.jpg',
    'titre_modele' => 'T Sleeper',
    'modele' => 'Chassis 4x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€115,843.-',    
];

//Scania data
$Scania_R_2009_Highline = [
    'id' => 'scania_r_2009_highline',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania R 2009 Highline',
    'titre_moteur' => 'Engine Power',
    'moteur' => '360 - 730 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 - 1400 l',
    'image' => 'images/trucks/Scania/Scania_R_2009_Highline.jpg',
    'titre_modele' => 'R 2009 Highline',
    'modele' => 'Highline Cabin',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '8 (Used Market)',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Variable (Used)',    
];


$Scania_R_2009_Normal = [
    'id' => 'scania_r_2009_normal',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania R 2009 Normal',
    'titre_moteur' => 'Engine Power',
    'moteur' => '360 - 730 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 - 1400 l',
    'image' => 'images/trucks/Scania/Scania_R_2009_Normal.jpg',
    'titre_modele' => 'R 2009 Normal',
    'modele' => 'Normal Cabin',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0 (Used Market)',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Variable (Used)',    
];


$Scania_R_2009_Topline = [
    'id' => 'scania_r_2009_topline',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania R 2009 Topline',
    'titre_moteur' => 'Engine Power',
    'moteur' => '360 - 730 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 - 1400 l',
    'image' => 'images/trucks/Scania/Scania_R_2009_Topline.jpg',
    'titre_modele' => 'R 2009 Topline',
    'modele' => 'Topline Cabin',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12 (Used Market)',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Variable (Used)',    
];

$Scania_R_Hight_Roof = [
    'id' => 'scania_r_high_roof',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania R High Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '370 - 660 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '965 - 1290 l',
    'image' => 'images/trucks/Scania/Scania_R_Hight_Roof.jpg',
    'titre_modele' => 'R High Roof',
    'modele' => 'High Roof Cabin',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '€210,630.-',    
];

$Scania_R_Hight_Roof_2 = [
    'id' => 'scania_r_high_roof_6x2_taglift',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania R High Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '500 - 660 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '965 - 1000 l',
    'image' => 'images/trucks/Scania/Scania_R_Hight_Roof_2.jpg',
    'titre_modele' => 'R High Roof',
    'modele' => 'High Roof Cabin 6x2 Taglift',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16-22',
    'titre_prix' => 'In-Game Price',
    'prix' => '€227,180.- / €315,865.-',    
];

$Scania_R_Normal_Roof = [
    'id' => 'scania_r_normal_roof',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania R Normal Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '370 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1290 l',
    'image' => 'images/trucks/Scania/Scania_R_Normal_Roof.jpg',
    'titre_modele' => 'R Normal Roof',
    'modele' => 'Normal Roof Cabin 4x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€120,580.-',    
];

$Scania_S_Hight_Roof = [
    'id' => 'scania_s_high_roof',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania S High Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '370 - 770 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1000 - 1290 l',
    'image' => 'images/trucks/Scania/Scania_S_Hight_Roof.jpg',
    'titre_modele' => 'S High Roof',
    'modele' => 'High Roof Cabin',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16',
    'titre_prix' => 'In-Game Price',
    'prix' => '€208,770.-',    
];

$Scania_S_Hight_Roof2 = [
    'id' => 'scania_s_high_roof_6x2_taglift_8x4',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania S High Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '560 - 770 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1000 l',
    'image' => 'images/trucks/Scania/Scania_S_Hight_Roof2.jpg',
    'titre_modele' => 'S High Roof',
    'modele' => 'High Roof Cabin 6x2 Taglift / 8x4',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '16-26',
    'titre_prix' => 'In-Game Price',
    'prix' => '€258,555.- / €326,946.-',    
];

$Scania_S_Normal_Roof = [
    'id' => 'scania_s_normal_roof',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania S Normal Roof',
    'titre_moteur' => 'Engine Power',
    'moteur' => '370 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '1290 l',
    'image' => 'images/trucks/Scania/Scania_S_Normal_Roof.jpg',
    'titre_modele' => 'S Normal Roof',
    'modele' => 'Normal Roof Cabin 4x2',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '€122,080.-',    
];

$Scania_Streamline_Normal = [
    'id' => 'scania_streamline_normal',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania Streamline Normal',
    'titre_moteur' => 'Engine Power',
    'moteur' => '360 - 730 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 - 1400 l',
    'image' => 'images/trucks/Scania/Scania_Streamline_Normal.jpg',
    'titre_modele' => 'Streamline Normal',
    'modele' => 'Normal Cabin',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0 (Used Market)',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Variable (Used)',    
];

$Scania_Streamline_Topline = [
    'id' => 'scania_streamline_topline',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania Streamline Topline',
    'titre_moteur' => 'Engine Power',
    'moteur' => '360 - 730 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 - 1400 l',
    'image' => 'images/trucks/Scania/Scania_Streamline_Topline.jpg',
    'titre_modele' => 'Streamline Topline',
    'modele' => 'Topline Cabin',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12 (Used Market)',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Variable (Used)',    
];

$Scania_Streamline_Topline2 = [
    'id' => 'scania_streamline_topline_v2',
    'marque' => 'Scania',
    'logo' => 'images/trucks/Scania/Scania_logo.png',
    'titre' => 'Scania Streamline Topline',
    'titre_moteur' => 'Engine Power',
    'moteur' => '360 - 730 cv',
    'titre_essence' => 'Tank Capacity',
    'essence' => '600 - 1400 l',
    'image' => 'images/trucks/Scania/Scania_Streamline_Topline2.jpg',
    'titre_modele' => 'Streamline Topline',
    'modele' => 'Topline Cabin',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12 (Used Market)',
    'titre_prix' => 'In-Game Price',
    'prix' => 'Variable (Used)',    
];

//Volvo data
$Volvo_FH_Classic_Globetrotter = [
    'id' => 'volvo_fh_classic_globetrotter',
    'marque' => 'Volvo',
    'logo' => 'images/trucks/Volvo/Volvo_logo.png',
    'titre' => 'Volvo FH Classic Globetrotter',
    'titre_moteur' => 'Engine Power',
    'moteur' => '420 - 540 ch',
    'titre_essence' => 'Tank Capacity',
    'essence' => '580 L',
    'image' => 'images/trucks/Volvo/Volvo_FH_Classic_Globetrotter.jpg',
    'titre_modele' => 'Model',
    'modele' => 'FH Classic',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '108 000 €',    
];

$Volvo_FH_Classic_Globetrotter_XL = [
    'id' => 'volvo_fh_classic_globetrotter_xl',
    'marque' => 'Volvo',
    'logo' => 'images/trucks/Volvo/Volvo_logo.png',
    'titre' => 'Volvo FH Classic Globetrotter XL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '420 - 540 ch',
    'titre_essence' => 'Tank Capacity',
    'essence' => '580 L',
    'image' => 'images/trucks/Volvo/Volvo_FH_Classic_Globetrotter_XL.jpg',
    'titre_modele' => 'Model',
    'modele' => 'FH Classic',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '117 000 €',    
];

$Volvo_FH_Classic_Globetrotter_XL2 = [
    'id' => 'volvo_fh_classic_globetrotter_xl2',
    'marque' => 'Volvo',
    'logo' => 'images/trucks/Volvo/Volvo_logo.png',
    'titre' => 'Volvo FH Classic Globetrotter XL2',
    'titre_moteur' => 'Engine Power',
    'moteur' => '420 - 540 ch',
    'titre_essence' => 'Tank Capacity',
    'essence' => '580 L',
    'image' => 'images/trucks/Volvo/Volvo_FH_Classic_Globetrotter_XL2.jpg',
    'titre_modele' => 'Model',
    'modele' => 'FH Classic',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',
    'titre_prix' => 'In-Game Price',
    'prix' => '126 000 €',    
];

$Volvo_FH_Classic_Sleeper = [
    'id' => 'volvo_fh_classic_sleeper',
    'marque' => 'Volvo',
    'logo' => 'images/trucks/Volvo/Volvo_logo.png',
    'titre' => 'Volvo FH Classic Sleeper',
    'titre_moteur' => 'Engine Power',
    'moteur' => '420 - 540 ch',
    'titre_essence' => 'Tank Capacity',
    'essence' => '580 L',
    'image' => 'images/trucks/Volvo/Volvo_FH_Classic_Sleeper.jpg',
    'titre_modele' => 'Model',
    'modele' => 'FH Classic',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '0',                
    'titre_prix' => 'In-Game Price',
    'prix' => '99 000 €',    
];

$Volvo_FH_Globetrotter = [
    'id' => 'volvo_fh_globetrotter',
    'marque' => 'Volvo',
    'logo' => 'images/trucks/Volvo/Volvo_logo.png',
    'titre' => 'Volvo FH Globetrotter',
    'titre_moteur' => 'Engine Power',
    'moteur' => '420 - 540 ch',
    'titre_essence' => 'Tank Capacity',
    'essence' => '650 L',
    'image' => 'images/trucks/Volvo/Volvo_FH_Globetrotter.jpg',
    'titre_modele' => 'Model',
    'modele' => 'FH',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '8',
    'titre_prix' => 'In-Game Price',
    'prix' => '136 000 €',    
];

$Volvo_FH_Globetrotter_XL = [
    'id' => 'volvo_fh_globetrotter_xl',
    'marque' => 'Volvo',
    'logo' => 'images/trucks/Volvo/Volvo_logo.png',
    'titre' => 'Volvo FH Globetrotter XL',
    'titre_moteur' => 'Engine Power',
    'moteur' => '420 - 540 ch',
    'titre_essence' => 'Tank Capacity',
    'essence' => '650 L',
    'image' => 'images/trucks/Volvo/Volvo_FH_Globetrotter_XL.jpg',
    'titre_modele' => 'Model',
    'modele' => 'FH',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '10',
    'titre_prix' => 'In-Game Price',
    'prix' => '145 000 €',    
];

$Volvo_FH_Globetrotter_XL2 = [
    'id' => 'volvo_fh_globetrotter_xl2',
    'marque' => 'Volvo',
    'logo' => 'images/trucks/Volvo/Volvo_logo.png',
    'titre' => 'Volvo FH Globetrotter XL2',
    'titre_moteur' => 'Engine Power',
    'moteur' => '420 - 540 ch',
    'titre_essence' => 'Tank Capacity',
    'essence' => '650 L',
    'image' => 'images/trucks/Volvo/Volvo_FH_Globetrotter_XL2.jpg',
    'titre_modele' => 'Model',
    'modele' => 'FH',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '12',
    'titre_prix' => 'In-Game Price',
    'prix' => '154 000 €',    
];

$Volvo_FH_Sleeper = [
    'id' => 'volvo_fh_sleeper',
    'marque' => 'Volvo',
    'logo' => 'images/trucks/Volvo/Volvo_logo.png',
    'titre' => 'Volvo FH Sleeper',
    'titre_moteur' => 'Engine Power',
    'moteur' => '420 - 540 ch',
    'titre_essence' => 'Tank Capacity',
    'essence' => '650 L',
    'image' => 'images/trucks/Volvo/Volvo_FH_Sleeper.jpg',
    'titre_modele' => 'Model',
    'modele' => 'FH',
    'titre_niveau' => 'Unlock Level',
    'niveau' => '6',
    'titre_prix' => 'In-Game Price',
    'prix' => '127 000 €',    
];

$DAF = [
    $DAF_2021_XF,
    $DAF_XF105_Space,
    $DAF_XF_Space,
    $DAF_XF105_Space_Cab_Plus,
    $DAF_XF_Space_Aero_4x2,
    $DAF_XF_Space_Aero_6x2,
    $DAF_2021_XG,
    $DAF_XF_Super_Space_4x2,
    $DAF_XF_Super_Space_6x2,
    $DAF_XF105_Super_Space,
    $DAF_2021_XG_Plus
];

$Iveco = [
    $Iveco_Stralis_Active_Space_310,
    $Iveco_Stralis_Active_Space_450_4x2,
    $Iveco_Stralis_Active_Super,
    $Iveco_Stralis_Active_Space_450_6x4,
    $Iveco_Stralis_HiWay_310,
    $Iveco_Stralis_Active_Space_Super_450,
    $Iveco_Stralis_HiWay_560,
    $Iveco_Stralis_Active_Space_Super_560
];

$MAN = [
    $MAN_TGX_Euro_5_XL,
    $MAN_TGX_Euro_6_XL,
    $MAN_TGX_GN,
    $MAN_TGX_Euro_5_XLX,
    $MAN_TGX_Euro_6_XL_6x2,
    $MAN_TGX_Euro_5_XL_6x4,
    $MAN_TGX_XLX,
    $MAN_TGX_Euro_6_XLX,
    $MAN_TGX_Euro_5_XXL,
    $MAN_TGX_Euro_6_XXL,
    $MAN_TGX_Euro_5_XXL_6x2,
    $MAN_TGX_GM,
    $MAN_TGX_Euro_6_XLX_6x4,
    $MAN_TGX_GX,
    $MAN_TGX_Euro_6_XXL_8x4,
    $MAN_TGX_GX_8x4
];

$MB = [
    $Mercedes_Actros_Low_Roof_Sleeper,
    $Mercedes_New_Actros_StreamSpace,
    $Mercedes_Actros_Low_Roof_Sleeper_6x4,
    $Mercedes_Actros_High_Roof_Sleeper,
    $Mercedes_Actros_High_Roof_Sleeper_6x2_4,
    $Mercedes_Actros_MegaSpace,
    $Mercedes_New_Actros_GigaSpace,
    $Mercedes_New_Actros_BigSpace,
    $Mercedes_Actros_High_Roof_Sleeper_6x4,
    $Mercedes_Actros_MegaSpace_6x2_4,
    $Mercedes_Actros_MegaSpace_598cv,
    $Mercedes_New_Actros_GigaSpace_8x4
];

$Renault = [
    $Renault_Magnum_Excellence,
    $Renault_Magnum_Excellence1,
    $Renault_Magnum_Excellence2,
    $Renault_Magnum_Excellence3,
    $Renault_Premium_High_Roof,
    $Renault_Premium_High_Roof2,
    $Renault_Premium_Normal_Roof,
    $Renault_Premium_Normal_Roof2,
    $Renault_T_High_Sleeper,
    $Renault_T_High_Sleeper2,
    $Renault_T_Sleeper
];

$Scania = [
    $Scania_R_2009_Highline,
    $Scania_R_2009_Normal,
    $Scania_R_2009_Topline,
    $Scania_R_Hight_Roof,
    $Scania_R_Hight_Roof_2,
    $Scania_R_Normal_Roof,
    $Scania_S_Hight_Roof,
    $Scania_S_Hight_Roof2,
    $Scania_S_Normal_Roof,
    $Scania_Streamline_Normal,
    $Scania_Streamline_Topline,
    $Scania_Streamline_Topline2
];

$Volvo = [
    $Volvo_FH_Classic_Globetrotter,
    $Volvo_FH_Classic_Globetrotter_XL,
    $Volvo_FH_Classic_Globetrotter_XL2,
    $Volvo_FH_Classic_Sleeper,
    $Volvo_FH_Globetrotter,
    $Volvo_FH_Globetrotter_XL,
    $Volvo_FH_Globetrotter_XL2,
    $Volvo_FH_Sleeper
];
?>